export const projects = [
  {
    id: "01",
    slug: "figures",
    title: "Figures",
    category: "Illustration",
    tags: ["Character Design", "Editorial"],
    year: "2024",
    description:
      "A set of editorial character illustrations exploring color contrast, gesture, and form across a small recurring cast.",
    link: "#",
    images: [
      { url: "https://picsum.photos/seed/figures1/500/700", rotate: -10, x: -50, y: 6 },
      { url: "https://picsum.photos/seed/figures2/500/700", rotate: 4, x: 0, y: -8 },
      { url: "https://picsum.photos/seed/figures3/500/700", rotate: 15, x: 50, y: 10 },
    ],
  },
  {
    id: "02",
    slug: "persona",
    title: "Persona",
    category: "Portrait",
    tags: ["AI-assisted", "Photo study"],
    year: "2024",
    description: "Portrait studies pairing photography with painterly retouching to explore identity and character.",
    link: "#",
    images: [
      { url: "https://picsum.photos/seed/persona1/500/700", rotate: -11, x: -50, y: 4 },
      { url: "https://picsum.photos/seed/persona2/500/700", rotate: 2, x: 0, y: -10 },
      { url: "https://picsum.photos/seed/persona3/500/700", rotate: 13, x: 50, y: 8 },
    ],
  },
  {
    id: "03",
    slug: "form",
    title: "Form",
    category: "3D",
    tags: ["Sculptural", "Studio render"],
    year: "2025",
    description: "Studio-lit 3D character renders focused on silhouette, material, and pose.",
    link: "#",
    images: [
      { url: "https://picsum.photos/seed/form1/500/700", rotate: -13, x: -50, y: 8 },
      { url: "https://picsum.photos/seed/form2/500/700", rotate: 3, x: 0, y: -6 },
      { url: "https://picsum.photos/seed/form3/500/700", rotate: 17, x: 50, y: 12 },
    ],
  },
  {
    id: "04",
    slug: "chromatic",
    title: "Chromatic",
    category: "Fashion",
    tags: ["Editorial", "Color study"],
    year: "2025",
    description: "A monochrome-meets-color fashion series playing with texture and contrast.",
    link: "#",
    images: [
      { url: "https://picsum.photos/seed/chroma1/500/700", rotate: -9, x: -50, y: 10 },
      { url: "https://picsum.photos/seed/chroma2/500/700", rotate: 5, x: 0, y: -8 },
      { url: "https://picsum.photos/seed/chroma3/500/700", rotate: 16, x: 50, y: 10 },
    ],
  },
  {
    id: "05",
    slug: "mythos",
    title: "Mythos",
    category: "Concept Art",
    tags: ["Narrative", "World-building"],
    year: "2023",
    description: "Concept illustrations built around a fictional mythology — figures, symbols, and mood.",
    link: "#",
    images: [
      { url: "https://picsum.photos/seed/mythos1/500/700", rotate: -8, x: -50, y: 6 },
      { url: "https://picsum.photos/seed/mythos2/500/700", rotate: 6, x: 0, y: -10 },
      { url: "https://picsum.photos/seed/mythos3/500/700", rotate: 14, x: 50, y: 12 },
    ],
  },
  {
    id: "06",
    slug: "kinetics",
    title: "Kinetics",
    category: "Motion",
    tags: ["Animation", "Interaction"],
    year: "2025",
    description: "Motion studies — small interactive and animated pieces exploring timing and easing.",
    link: "#",
    images: [
      { url: "https://picsum.photos/seed/kinetics1/500/700", rotate: -12, x: -50, y: 4 },
      { url: "https://picsum.photos/seed/kinetics2/500/700", rotate: 2, x: 0, y: -8 },
      { url: "https://picsum.photos/seed/kinetics3/500/700", rotate: 18, x: 50, y: 14 },
    ],
  },
];
